engines:
  eslint:
    enabled: true
    channel: "eslint-3"
  csslint:
    enabled: true
  duplication:
    enabled: true
    languages:
    - javascript:
  fixme:
    enabled: true
  nodesecurity:
    enabled: true
  scss-lint:
    enabled: true
